<?php include 'includes/head.php';?>
<?php include 'includes/header.php';?>
<main>
	<!-- introBlock -->
	<div class="introBlock innerPagesBanner">
		<!-- ibsColumn -->
		<article class="ibsColumn text-center d-flex w-100 position-relative text-white fontAlter">
			<div class="alignHolder w-100 d-flex align-items-center">
				<div class="align w-100 py-8 py-md-14 py-lg-20">
					<div class="container">
						<div class="row">
							<div class="col-12">
								<h1 class="text-white font-weight-bold mb-4 h2Large">FAQs</h1>
								<ul class="list-unstyled cbbPageList text-capitalize d-flex align-items-center justify-content-center flex-wrap mb-0 p-0">
									<li><a href="index.html">Home</a></li>
									<li><a href="about.html">About</a></li>
									<li>FAQs</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<span class="bgCover ibsBgWrap w-100 h-100 position-absolute" style="background-image: url(assets/images/m-2-r.png);"></span>
		</article>
	</div>
	<!-- faqSectionBlock -->
	<article class="faqSectionBlock py-10 py-md-15 pt-lg-14 pb-lg-13">
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-10 offset-md-1 col-xl-6 offset-xl-3">
					<header class="headingHead fzMedium mb-8 mb-md-12 text-center">
						<h2>
							<strong class="d-block text-uppercase hTitle fwMedium mb-4">Find Answers Below</strong>
							<span class="d-block">Frequently Asked Questions</span>
						</h2>
						<p>If you can't find an answer below, please contact us or send us an email to <a href="admin@kintsugi-garage.com">admin@auctionsheetcheck.com</a></p>
					</header>
				</div>
			</div>
			<div class="row">
				<div class="col-12 col-md-4 col-lg-3 mb-6">
					<div class="mr-md-n3 mr-lg-n5">
						<aside class="dscSidebar pt-1 ml-xl-n5">
							<div class="widget mb-6 mb-lg-10 widgetHelp bg-primary rounded-lg pt-8 px-6 pb-8 position-relative text-center text-white">
								<div class="captionHolder">
									<i class="icn icomoon-information1 text-secondary d-block mb-3"><span class="sr-only">icon</span></i>
									<h3 class="h3 h3Large text-white mb-2">Need help?</h3>
									<p>Don't hesitate to contact us to ask something or consult.</p>
									<a href="contact.html" class="btn btnThemeAlt text-capitalize position-relative border-0 p-0 btnMinMedium" data-hover="Contact us">
									<span class="d-block btnText">Contact us</span>
									</a>
									<i class="whWatermarkIcn icomoon-helpc position-absolute"><span class="sr-only">icon</span></i>
								</div>
								<span class="bgCover bgImg w-100 h-100 position-absolute" style="background-image: url(images/bgPattern02.png);"></span>
							</div>
						</aside>
					</div>
				</div>
				<div class="col-12 col-md-8 col-lg-9">
					<div class="pl-md-5 pl-xl-15 fontAlter">
						<div class="accordion faqAccordion mb-8 mb-md-12 mb-lg-16 mb-xl-20" id="ctdepartsAccordion">
							<div class="ctaccRow mb-4">
								<div class="ctaccOpener">
									<a class="fontAlter" href="#ctr1" data-toggle="collapse" aria-expanded="false" aria-controls="ctr1"> What’s the option for not found chassis?</a>
								</div>
								<div class="collapse ctaccSlide" id="ctr1" data-parent="#ctdepartsAccordion">
									<div class="overflow-hidden px-5 pb-1">
										<p>If the auction sheet against your chassis is not available you can contact us through email for manual check-in our report+ services.</p>
									</div>
								</div>
							</div>
							<div class="ctaccRow mb-4">
								<div class="ctaccOpener">
									<a class="fontAlter" href="#ctr2" data-toggle="collapse" aria-expanded="false" aria-controls="ctr2">Is the report generated by japan?</a>
								</div>
								<div class="collapse show ctaccSlide" id="ctr2" data-parent="#ctdepartsAccordion">
									<div class="overflow-hidden px-5 pb-1">
										<p class="mb-6">We always send the original auction sheet Not a single thing added by the company.</p>
									</div>
								</div>
							</div>
							<div class="ctaccRow mb-4">
								<div class="ctaccOpener">
									<a class="fontAlter" href="#ctr3" data-toggle="collapse" aria-expanded="false" aria-controls="ctr3"> If auction sheet not received?</a>
								</div>
								<div class="collapse ctaccSlide" id="ctr3" data-parent="#ctdepartsAccordion">
									<div class="overflow-hidden px-5 pb-1">
										<p>If you did not receive your auction sheet you can contact us via email and we will send you manually.</p>
									</div>
								</div>
							</div>
							<div class="ctaccRow mb-4">
								<div class="ctaccOpener">
									<a class="fontAlter" href="#ctr4" data-toggle="collapse" aria-expanded="false" aria-controls="ctr4">I have made the payment. How will I receive the Auction Sheet?</a>
								</div>
								<div class="collapse ctaccSlide" id="ctr4" data-parent="#ctdepartsAccordion">
									<div class="overflow-hidden px-5 pb-1">
										<p>After depositing the payment you will receive your auction sheet within a few minutes in your email.</p>
									</div>
								</div>
							</div>
							<div class="ctaccRow mb-4">
								<div class="ctaccOpener">
									<a class="fontAlter" href="#ctr5" data-toggle="collapse" aria-expanded="false" aria-controls="ctr5">Which information provide in auctions sheet?</a>
								</div>
								<div class="collapse ctaccSlide" id="ctr5" data-parent="#ctdepartsAccordion">
									<div class="overflow-hidden px-5 pb-1">
										<p>All the information about your vehicle mileage, grade, accidental, repair, etc mention in the report.</p>
									</div>
								</div>
							</div>
							<div class="ctaccRow mb-4">
								<div class="ctaccOpener">
									<a class="fontAlter" href="#ctr6" data-toggle="collapse" aria-expanded="false" aria-controls="ctr6">How to pay for auctions sheet?</a>
								</div>
								<div class="collapse ctaccSlide" id="ctr6" data-parent="#ctdepartsAccordion">
									<div class="overflow-hidden px-5 pb-1">
										<p>You can pay with Visa/master, Debit/credit card and PayPal.</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</article>
</main>
<?php include 'includes/footer.php';?>
<?php include 'includes/script.php';?>